os: linux
dist: bionic
language: python
jobs:
 include: 
 - name: “test” # existing functionality
   script: # existing functionality
    - python --version
 - name: “sbom”
   script: # existing functionality
     - cd python
     - pip install -r requirements.txt
   addons:
     sbom:
       on:
         branch: 'main'
         pr: true
       # condition: false
       run_phase: "after_success" #
       output_format: "spdx-json" # 
       output_dir: "/test" # 
       input_dir: "/python" #
